#!/bin/bash

### This script generates index.html, which loads all needed javascript and
### css for the app.

pwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ASSET_ROOT=""
SEARCH_PATH=""
source "$pwd/include.sh"

## -----------------------------------------------------------------------------
## generate extra
## -----------------------------------------------------------------------------
extra='<base href="/">'

## -----------------------------------------------------------------------------
## generate CSS links
## -----------------------------------------------------------------------------
css=""
for x in $(all_css); do
	css="${css}$(print_css $x)"
done

## -----------------------------------------------------------------------------
## generate JS includes
## -----------------------------------------------------------------------------
js=""
for x in $(all_js); do
	js="${js}$(print_js $x)"
done

## -----------------------------------------------------------------------------
## generate inline JS
## -----------------------------------------------------------------------------
for x in $(inline_js); do
	js="${js}$(print_inline_js $x)"
done

## -----------------------------------------------------------------------------
## put it all together
## -----------------------------------------------------------------------------
index="$(cat views/layouts/default.html)"
index="$(do_replace "$index" '{{extra}}' "$extra")"
index="$(do_replace "$index" '{{gencss}}' "$css")"
index="$(do_replace "$index" '{{genjs}}' "$js")"

# send our generated data into their restecpive files
echo -ne "$index" > index.html

