#!/bin/bash

function do_make () {
	make \
		| grep -v 'Nothing to be done' \
		| grep -v '\(Entering\|Leaving\) directory'
}

function changes () {
	inotifywait.exe -r --exclude='(\.git|node_modules)' -q .
}

do_make
echo "- Watching..."
while changes; do
	do_make
	echo "- Make done, watching"
done

