#!/bin/bash

### This script generates index.html, which loads all needed javascript and
### css for the app.

pwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ASSET_ROOT=""
SEARCH_PATH=""
source "$pwd/../../scripts/include.sh"

## -----------------------------------------------------------------------------
## generate extra
## -----------------------------------------------------------------------------
extra='<base href="../">'

## -----------------------------------------------------------------------------
## generate CSS links
## -----------------------------------------------------------------------------
css="$(
	echo "$(all_css)" \
		| sed 's|^|<link rel=\"stylesheet\" href=\"/|' \
		| sed 's|$|">|'
)"
css="${css}\n<link rel=\"stylesheet\" href=\"/tests/lib/vnd/jasmine/jasmine.css\">"
css="${css}\n<link rel=\"stylesheet\" href=\"/tests/css/main.css\">"

## -----------------------------------------------------------------------------
## generate JS includes
## -----------------------------------------------------------------------------
js="$(
	echo "$(all_js)" \
		| sed 's|___| |g' \
		| sed 's|^|<script src="/|' \
		| sed 's|$|"></script>|'
)"
# load in our tests
js="${js}\n<script src=\"/tests/lib/vnd/jasmine/jasmine.js\"></script>"
js="${js}\n<script src=\"/tests/lib/vnd/jasmine/jasmine-html.js\"></script>"
js="${js}\n<script src=\"/tests/lib/vnd/jasmine/boot.js\"></script>"
js="${js}\n<script src=\"/tests/load.js\"></script>"
js="${js}\n$(
	find tests/{data,tests} -name "*.js" \
		| sort \
		| sed 's|^|<script src="/|' \
		| sed 's|$|"></script>|'
)"


## -----------------------------------------------------------------------------
## put it all together
## -----------------------------------------------------------------------------
index="$(cat views/layouts/default.html)"
index="$(do_replace "$index" '{{extra}}' "$extra")"
index="$(do_replace "$index" '{{gencss}}' "$css")"
index="$(do_replace "$index" '{{genjs}}' "$js")"

# send our generated data into their restecpive files
echo -ne "$index" > tests/index.html


